CREATE TABLE KC_RECORD (
  NAMESPACE VARCHAR(64) NOT NULL,
  RECORD_KEY VARCHAR(256) NOT NULL,
  PAYLOAD CLOB NOT NULL,
  PAYLOAD_SHA256 CHAR(64) NOT NULL,
  REVISION BIGINT DEFAULT 1 NOT NULL,
  DELETED CHAR(1) DEFAULT 'N' NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_KC_RECORD PRIMARY KEY (NAMESPACE, RECORD_KEY),
  CONSTRAINT CK_KC_RECORD_DELETED CHECK (DELETED IN ('N', 'Y'))
);

