CREATE TABLE KC_MIGRATION_BATCH (
  BATCH_ID VARCHAR(64) PRIMARY KEY,
  SOURCE_KIND VARCHAR(32) NOT NULL,
  STATUS VARCHAR(24) NOT NULL,
  RECORD_COUNT BIGINT DEFAULT 0 NOT NULL,
  SOURCE_SHA256 CHAR(64),
  RESULT_SHA256 CHAR(64),
  STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  COMPLETED_AT TIMESTAMP,
  ERROR_SUMMARY VARCHAR(2000)
);

